Description: >
  DungNQ21 | Udacity 2023
  AWS-CloudFormation script to create a LoadBalancer.

############################### Parameters ################################
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: Udagram

############################### Resources #################################
Resources:
  UdagramLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: UdagramLoadBalancer
      Subnets:
        - Fn::ImportValue: !Sub '${EnvironmentName}-PUB1-SN'
        - Fn::ImportValue: !Sub '${EnvironmentName}-PUB2-SN'
      SecurityGroups:
        - Fn::ImportValue: !Sub '${EnvironmentName}-LB-SG'
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: "true"
        - Key: access_logs.s3.bucket
          Value:
            Fn::ImportValue: !Sub '${EnvironmentName}-S3Logs'

  UdagramLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref UdagramLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Fn::ImportValue: !Sub '${EnvironmentName}-TG'

############################### Outputs #################################
Outputs: 
  Website:
    Description: The Public DNS for the LoadBalancer
    Value: !Join ['', ['http://', !GetAtt [UdagramLoadBalancer, DNSName]]]